apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-app-servicemonitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: web-app
  endpoints:
  - port: http
    path: /metrics
